### ISSUE TITLE
Example without SubscriptionManager

### ISSUE THREAD

**Issue by Knaackee** [davidyaha/graphql-redis-subscriptions#104]
On the [graphql-subscriptions github page](https://github.com/apollographql/graphql-subscriptions) i found 

```
SubscriptionManager @deprecated
SubscriptionManager is the previous alternative for using graphql-js subscriptions directly, and it's now deprecated.
```

Could someone please provide a example without the SubscriptionManager.

Thanks in advance!

**Comment by davidyaha** [comment]
Hello @Knaackee!

The API is almost identical to using the Event Emitter PubSub instance that is provided on the `graphql-subscriptions` package.
We do have examples on the test files:
Getting an AsyncIterator - https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/test/tests.ts#L304-L306
Publishing an event - https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/test/tests.ts#L331

And the rest of the usage is same as graphql-subscriptions: https://github.com/apollographql/graphql-subscriptions/blob/master/README.md#getting-started-with-your-first-subscription

If that helps you, please consider submitting a PR to the README with an up to date example.
Thanks!

**Comment by davidyaha** [comment]
@Knaackee Gone ahead and done it myself, Thanks for the insight.
Please take a look on the updated readme for examples and LMK if that worked for you.

Closing for now as was fixed with https://github.com/davidyaha/graphql-redis-subscriptions/commit/dd70b23d6f8da2841a0e807a25a1d1bddbbad5ab

**Comment by Knaackee** [comment]
Thanks! But whats still not clear to me is how to set the the redis pubsub to the SubscriptionServer without the (gone) SubscriptionManager.

**Comment by davidyaha** [comment]
@Knaackee You don't need to worry about the SubscriptionManager anymore as the graphql engine uses the schema itself to handle subscriptions. 
I would recommend heading over to subscriptions-transport-ws and read their docs  https://github.com/apollographql/subscriptions-transport-ws#server

Does that help?

**Comment by Knaackee** [comment]
But how does the SubscriptionServer knows about the messages pushed to the pubsub? The clients browser is connected to a websocket server > subscription server so how does the message come to the user ?

**Comment by davidyaha** [comment]
Tried to make the flow more apparent:

Subscribe flow:
```
Browser --subscribe x--> WS server --> graphql.subscribe --> RedisPubSub.asyncItrable(x) 
--SUBSCRIBE x--> Redis
```

Publish flow: 
```
Browser --mutation x--> graphql.mutate --> RedisPubSub.publish(x) --PUBLISH x--> Redis 
--> RedisPubSub.asyncIterator.next(x) --> graphql.subscribe.resolve(x) --> WS server
--> Browser
```

Does that makes sense? 🤔 

I suggest reading the code of this package and of the `subscriptions-transport-ws` package to get clearer understanding, but let me know if you have more questions.

**Comment by Knaackee** [comment]
Yes! I found the missing piece. Thank You!

**Comment by Knaackee** [comment]
Thank you very much for your help! 

I have the connection between the browser and client established
as well as the resolver publishing to the Redis PubSub. But whats still unclear is how 
i pass the PubSub to the SubscriptionService.

Imagine the following scenario:
I have 3 Webserver with the frontend, backend and the Websocket server. I have one redis server. Now i publish to this server. No problem. But (at my understanding) at some point the SubscriptionService needs to pick the published message in order to deliver to the client.

For this to work there must be a connection between the SubscriptionService and the PubSub system.

If my guessing was true. How i initialise the SubscriptionService with the Redis PubSub?

**Comment by davidyaha** [comment]
Yes you are right and it has the connection through the schema object.
Consider this SubscriptionsServer:
```javascript
const subscriptionServer = SubscriptionServer.create(
  {
    schema,
    execute,
    subscribe,
  },
  {
    server: websocketServer,
    path: '/graphql',
  },
);
```
It get's the schema object as a parameter. The schema object has the connection to the redis through it's asyncIterator: 

```graphql
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type Subscription {
    somethingChanged: Result
}

type Result {
    id: String
}
```

```javascript
const SOMETHING_CHANGED_TOPIC = 'something_changed';

export const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: () => pubsub.asyncIterator(SOMETHING_CHANGED_TOPIC), // When this is executed, the current server will subscribe to the redis topic and wait for events
    },
  },
}
```

Each of your servers will run this subscribe resolver whenever a client send a subscribe operation to the SubscriptionServer. When an event is published on redis, they will get it, run the rest of the resolvers and (e.g. the `Result` type resolvers) and send the resulting message to the client.

Hope it helps :)
LMK how it goes.

**Comment by davidyaha** [comment]
Do you see a SUBSCRIBE message on the redis monitor?

**Comment by Knaackee** [comment]
No, i only get the following 

```
1513766296.760226 [0 127.0.0.1:55881] "info"
1513766296.762157 [0 127.0.0.1:55880] "publish" "HEALTH_STATUS_REQUESTED" "{\"healthStatus\":{\"status\":\"ok Wed Dec 20 2017 11:38:16 GMT+0100 (CET)\"}}"
```

**Comment by davidyaha** [comment]
Do the client send a subscribe query that fits the schema? Does it work with the regular pubsub from the graphql-subscriptions package?

**Comment by Knaackee** [comment]
Yes, the client sends a correct request. I do it with Graphiql. I get "Your subscription data will appear here after server publication!". 

**But wait**, I just debugged the subscribe resolver and noticed that he doesn't get called. I have to debug why that happens.

**Comment by jalalat** [comment]
Hi @davidyaha  there are 4 different aspects:

1) Server setup - on which you mentioned about using SubscriptionsServer. It is clear now.
2) Client setup - Not clear what setup to use. I was using SubscriptionClient to connect it with my app. Documentation talks about SubscriptionManager being deprecated. What we should use instead?
3) CreatingPubSub on Server - it is very much clear 
4) Using PubSub on server side to publish and subscribe - it is also clear

**Comment by davidyaha** [comment]
Hey @jalalat! That's good to hear that points 1,3,4 are clearer now :)

About the client setup, that's actually not in the scope of this package at all.
That part is handled by the ws-transport package and apollo client. You can get more information on their readme: https://github.com/apollographql/subscriptions-transport-ws#client-browser
and docs: https://www.apollographql.com/docs/react/features/subscriptions.html#subscriptions-client

Hope that helps :)
